// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "shop-service/internal/domain"

	mock "github.com/stretchr/testify/mock"

	purchase "shop-service/internal/repository/purchase"
)

// PurchaseRepository is an autogenerated mock type for the PurchaseRepository type
type PurchaseRepository struct {
	mock.Mock
}

// CreatePurchase provides a mock function with given fields: ctx, req
func (_m *PurchaseRepository) CreatePurchase(ctx context.Context, req purchase.CreatePurchaseRequest) (*domain.Purchase, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePurchase")
	}

	var r0 *domain.Purchase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, purchase.CreatePurchaseRequest) (*domain.Purchase, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, purchase.CreatePurchaseRequest) *domain.Purchase); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Purchase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, purchase.CreatePurchaseRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPurchaseSummary provides a mock function with given fields: ctx, req
func (_m *PurchaseRepository) GetPurchaseSummary(ctx context.Context, req purchase.PurchaseSummaryRequest) ([]*purchase.PurchaseSummary, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetPurchaseSummary")
	}

	var r0 []*purchase.PurchaseSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, purchase.PurchaseSummaryRequest) ([]*purchase.PurchaseSummary, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, purchase.PurchaseSummaryRequest) []*purchase.PurchaseSummary); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*purchase.PurchaseSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, purchase.PurchaseSummaryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPurchaseRepository creates a new instance of PurchaseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPurchaseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PurchaseRepository {
	mock := &PurchaseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
